### ISSUE TITLE
Add variation in particle generation

### ISSUE THREAD

**Issue by RajivPerera-Robotics** [a-matsoukas/robot_localization#5]
-Add variation in particle generation: input the standard deviation
-refactor how we re initialize particles, which arguments we are passing: tuples of value, standard dev or even numpy array or list: ordered triple?

**Comment by JohnnyMaBoi** [comment]
optimize the weight accessing

**Comment by RajivPerera-Robotics** [comment]
rename variables:

transformation to odom -> transform to map
update particles with odom/laser -> move particles with odom, update particles with laser
